# Generated by Django 5.2.3 on 2025-07-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_property_image_property_image_url_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
