# Generated by Django 5.2.3 on 2025-07-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_profile_is_email_verified_profile_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="furnished",
        ),
        migrations.RemoveField(
            model_name="property",
            name="has_ac",
        ),
        migrations.RemoveField(
            model_name="property",
            name="has_garden",
        ),
        migrations.RemoveField(
            model_name="property",
            name="has_heating",
        ),
        migrations.RemoveField(
            model_name="property",
            name="has_parking",
        ),
        migrations.RemoveField(
            model_name="property",
            name="has_pool",
        ),
        migrations.AddField(
            model_name="property",
            name="amenities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="property",
            name="deposit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
