# Generated by Django 5.2.3 on 2025-07-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_remove_property_furnished_remove_property_has_ac_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="deposit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
