# Generated by Django 5.2.3 on 2025-07-24 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_property_deposit"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitude of the property",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitude of the property",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="property_videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(["mp4", "mov", "avi"])
                ],
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="is_featured",
            field=models.BooleanField(default=True),
        ),
    ]
