# Generated by Django 5.2.3 on 2025-08-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_property_latitude_property_longitude_property_video_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="guest",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
