# Generated by Django 5.2.3 on 2025-08-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_booking_guest_alter_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment_data",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                ],
                default="Approved",
                max_length=10,
            ),
        ),
    ]
