# Generated by Django 5.2.3 on 2025-08-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_booking_payment_data_alter_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="monthly_due_dates",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_type",
            field=models.CharField(
                choices=[("full", "Full Amount"), ("monthly", "Monthly")],
                default="full",
                max_length=10,
            ),
        ),
    ]
