# Generated by Django 5.2.3 on 2025-08-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_booking_monthly_due_dates_booking_payment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="payment_type",
            field=models.CharField(
                choices=[("monthly", "Monthly")], default="full", max_length=10
            ),
        ),
    ]
